### ISSUE TITLE
Season and Show objects now contain a method called getStreamURL

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#12]
The `Series` and `Show` objects now contain a method called `getStreamURL` which produces an invalid URL.

Should the code be restructured to account for this? Thinking outloud, mabe the inheritance could be something like:

`Video <- PlayableVideo <- Episode`
and
`Video <- Show`

**Comment by mjs7231** [comment]
Good catch.

**Comment by mjs7231** [comment]
Adding another nested object is probably is a more perfect solution, but I want to avoid that complexity for now since this is currently a one-off. In the future if we find more cases where we need to distinguish between playable videos and non-playable videos we should break it apart as described above.

The commit below simply raises an Unsupported exception if called with the wrong video type.

commit 05ef43bddcf96193de96689a082b118ef71a3bdd
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Jun 4 10:55:30 2015 -0400
Raise exception if trying to get streamURL for Show or Season
