### ISSUE TITLE
Requests not using Session

### ISSUE THREAD

**Issue by pannal** [mjs7231/python-plexapi#30]
Hey,

I've been looking through your code to decide whether to replace https://github.com/fuzeman/plex.py in  https://github.com/pannal/Sub-Zero.bundle with your library.

What I've noticed is that you are using plain requests.get calls for your HTTP queries, and you don't initialize a Session to get the advantages of keepalive. Is there any reason for this?

**Comment by mjs7231** [comment]
Hey Pannal,

Thanks for all the enhancement requests.  All the ideas you posted seem like they would be great additions. I'll probably start with the config options because they seem the easiest at this point.  -- As far as this bug (#30); I'll have to read up on requests a bit more before I understand enough about the requests session api. This project is actually the first time I used the that package.

Mike

**Comment by pannal** [comment]
Thanks for the quick answer :)

Have a look at those:
http://docs.python-requests.org/en/latest/api/#request-sessions

(implementation)
https://github.com/fuzeman/plex.py/blob/master/plex/request.py
https://github.com/fuzeman/plex.py/blob/master/plex/core/http.py

**Comment by havardgulldahl** [comment]
So, fwiw, I've added session support in my tree, take a look at https://github.com/havardgulldahl/python-plexapi/commit/b6569dc6a3ade52ac1e8624554e9f0d422e78443 

I opted to make it an optional argument to `PlexServer()`, so that the caller would have full control of headers and proxy setup and the like. 

Here's how I use it in a real world project (notice the last line):

```python

def get_requests_session(proxy_config, user_agent):
    proxy = httpclient.format_proxy(proxy_config)
    full_user_agent = httpclient.format_user_agent(user_agent)

    session = requests.Session()
    session.proxies.update({'http': proxy, 'https': proxy})
    session.headers.update({'user-agent': full_user_agent})

    return session


class Example(object):
    def __init__(self):
        self.session = get_requests_session(proxy_config=config['proxy'],
                                            user_agent='%s/%s' % (mopidy_plex.Extension.dist_name,
                                                                  mopidy_plex.__version__)
                                           )
        self.plex = PlexServer(config['plex']['server'], session=self.session)
```

This is more or less verbatim from the example code in https://mopidy.readthedocs.org/en/latest/extensiondev/#example-using-requests-sessions, and it works just fine.


Comments are more than welcome.

**Comment by mjs7231** [comment]
@havardgulldahl - I'm planning to pull this in pretty much straight from your example. Do you think it's worth defaulting the session to anything if it's not supplied?

**Comment by havardgulldahl** [comment]
@mjs7231 Yes, you're right, there's no reason not to use sessions. In my current implementation `PlexServer` defaults to cold-calling `requests.get` every time, but something in the lines of this pseudo code is  better:

```python

class PlexServer
    if session is None:
        self.session = requests.Session()
    self.method = self.session.get

```

**Comment by mjs7231** [comment]
commit cc58b87c9bf605dc8cbe578c01b3b01fbb2e9aba
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Tue Mar 15 23:53:04 2016 -0400
Default to always use a session
