### ISSUE TITLE
PlexClient.sendCommand is broken

### ISSUE THREAD

**Issue by Hellowlol** [mjs7231/python-plexapi#51]
https://github.com/mjs7231/python-plexapi/blob/master/plexapi/client.py#L68
there is no self.address it was removed in 84a6999ed709726fdb3202ae6dc9cca8d8f43515

**Comment by mjs7231** [comment]
Thanks, I need more testing in this area.  I wasn't able to get the proxy working on my local setup so moved on for now and disabled the tests.  I'll definetly have this path tested before releasing v2.0.

Have you had luck getting the proxy commands to work?

**Comment by mjs7231** [comment]
Hazaa, I got this working!  It seems at some point in the last year or so Plex started using a different URL scheme to proxy commands through the server. It used to be `/system/players/<client_ip>/<command>` and has since changed to be the same exact path as the connecting directly to the client takes `/player/<command>` but also requires passing the header `X-Plex-Target-Client-Identifier` instead of specifying the IP address. This page gave the me clue I was looking for: https://github.com/plexinc/plex-media-player/wiki/Remote-control-API

commit 610bf16ce3fe64c3d56c28b323bf482959db0875
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Tue Apr 5 23:32:49 2016 -0400
Client control via proxy working; Re-enable control via proxy tests
