### ISSUE TITLE
Episode and Season numbering

### ISSUE THREAD

**Issue by ttufts** [mjs7231/python-plexapi#54]
The Plex XML output orders Seasons and Episodes. Plex JS uses this ordering to name episodes in the Plex GUI. 

Should be able to set 
episode_obj.episode_number = X 
episode_obj.season_number = X 
in the Episode class. 

Also would be nice to have a definite integer attribute for season number as well, could be handled in the same way.

**Comment by ttufts** [comment]
Expect a pull request for this added functionality in the next few hours. Working on it now.

**Comment by ttufts** [comment]
The major problem with implementing this is the modular way that the XML parsing is done. When an item is built it doesn't have any context of where it was in the XML that came from Plex. 

To pass this info down to the Season/Episode objects will require passing down an 'index' parameter into the object. 

OR

after an item has been built, if it is part of a list it's index can be added to the item as an 'index' attribute, which could then be read. The downside to this is that the object is already created, and the listItems function doesn't know what type of object it is. It's a bit ugly to put in a 'if type == season' conditional in the listItems function, but it's also very ugly to persist 'index' as a parameter way down to the leaf object constructors.

**Comment by mjs7231** [comment]
I've been thinking about this problem a bit as well. The Season objects used to include `index` and `parentTitle` attributes, but seems to have been removed sometime in the last few months.  not sure about the best way to solve it.

The problem with knowing where you came from is not ideal either because you may not always to the the a Season object through it's Show. You can go directly there if you wanted. Maybe we do a combination of both.  Pass in the index if we have it, make a second request to the Show (from the Season) if we request index and do not have it yet?

**Comment by ttufts** [comment]
Pull Request #55 should solve this issue. Only added 5 lines I think. Was pretty easy to add and I think it's a fairly elegant solution.

**Comment by mjs7231** [comment]
commit 36b5d12a192ac0574c33b0849f1087b17f805c9b
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu May 19 23:42:06 2016 -0400
Add back missing index value from Show,Season,Episode; Make season numbers a bit easier to fetch
