### ISSUE TITLE
Read timed out.

### ISSUE THREAD

**Issue by michary** [mjs7231/python-plexapi#57]
Hey guys,

Sometimes I get timeout exceptions:
`[ERROR]: Exception: HTTPConnectionPool(host='localhost', port=32400): Read timed out. (read timeout=5)`

After a quick look in the source, I think there should be a 30 second timeout, or am I wrong?

Thanks
Michael

**Comment by mjs7231** [comment]
Yea I should increase it. It was lowered a long time ago because when connecting to a server through the local and external urls provided by Plex.tv I needed to try connecting to all 2 or 3 ips at the same time to find the one that worked. Waiting 30s to try ips that didn't work was not ideal. There must be a way that I can set the timeout lower only during that one call instance.

**Comment by mjs7231** [comment]
Ahh sorry, this change was already made a while back on the master branch, it just hasn't made its way to pip yet.  Expect version 2.x to hit pip in a week or two, but be aware there are a few api naming changes.
