### ISSUE TITLE
unneeded reload()

### ISSUE THREAD

**Issue by Hellowlol** [mjs7231/python-plexapi#77]
I'm in the progress of adding some undocumented search features to plexapi (so i can use it with htpc manager) and i come across some strange behavior where a object is reload.

https://github.com/mjs7231/python-plexapi/blob/master/plexapi/video.py#L236 seems to be unneeded since ```/library/metadata/<key>/allLeaves``` includes directors, actors etc. 

I have added a test that checks the resolution of eps and compares it to what plex returns when using section search with params {"resolution<": 720}.

Is the reload required for something else that im not seeing there? 
(removing the unneeded reload reduced the test time to 40 sec from over 10+minutes
I have 723 shows but there is over 23k episodes. Ill rather to 723 http requests then 23k+.)

I love the fact that we can use our own session object. That really great since requests has a really nice api but its really slow. Now i can just use human_curl instead (with a small patch)

There is also a small bug where the c.key is double quoted when calling listchoices. I'm gonna included that in a pr

**Comment by mjs7231** [comment]
The idea behind the reload and NA is that if an objects attribute is requested and the main url for that object has not been loaded yet, we will reload it in the background automatically. If everything you need was in the original (shortened) representation of the object and you didn't use any other unloaded attributes of the object, the reload should not happen. I feel over time this mechanism got a bit rusty and probably needs to be revisited.

I also at some point want to remove the whole NA thing all together, it feels dirty, but after a year I always forget what the roadblock to removing it was.

**Comment by mjs7231** [comment]
@Hellowlol Did I see you took a stab at this in a recent pull request?

**Comment by Hellowlol** [comment]
Yeah I did. It's a lot better but I'm not sure i got them all.

**Comment by mjs7231** [comment]
Just adding a reminder to discuss. The reason this is marked as question is because of the removed `if` statement in the pull request linked below. While this does speed up your particular use case, it introduces a bug.

When loading search results for movies or shows we often see 3 actors (roles) listed. We populate the roles with those 3 people. However, we technically don't have all the roles that Plex knows about for that show, so it's still considered a partial object and we need to load the full show url to fetch all roles (beyond the 3 listed in the search result). by commenting out that if statement, we don't load the full object and will won't see more than 3 roles populated.

I think the correct fix might be a new method or option in PlexPartialObject to tell partial objects that "Its OK if you don't load everything, I don't want you to because it's slow!"

https://github.com/mjs7231/python-plexapi/pull/88

**Comment by Hellowlol** [comment]
@mjs7231 At the time i wasnt aware that search only added 3 actors. Because i reloaded the object and still listed 3 actors. There was a bug so the initpath of the object was wrong so it only reloaded the same info. I have fixed this and the location bug in my test pr. 

I like your suggestion so we can grab as much info as we can at first pass. I have no idea how to handle this :P

**Comment by mjs7231** [comment]
This is fixed on the 3.0.0 branch.
